import = [
    "~/.config/alacritty/themes/themes/citylights.toml"
]

[font]
size = 9.0

[font.bold]
family = "Dejavu Sans Mono"
style = "Bold"

[font.bold_italic]
family = "Dejavu Sans Mono"
style = "Bold Italic"

[font.italic]
family = "Dejavu Sans Mono"
style = "Italic"

[font.normal]
family = "Dejavu Sans Mono"
style = "Regular"
